### ISSUE TITLE
Loading and saving recipies does not work correctly

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#41] opened 2021-01-27 16:17 UTC
Using version 1.2.1 from the BApp store.

Saving and loading recipes does not work correctly. How to reproduce:

1. Create a recipe 
2. Save the recipe
3. Modify the recipe in Burp
4. Reload the previous state of the recipe from the file
5. The recipe in Burp is not correctly replaced with the one from the file. Instead, some elements of the recipe from the file get added to the recipe in Burp

**Comment by qtc-de** [comment] 2021-01-30 14:34
Thanks for the report. We will look into this soon.

**Comment by fhaag95** [comment] 2023-06-21 08:15
Sorry for the long waiting time. Currently we cannot reproduce this issue. We assume it was also fixed in a previous commit. Furthermore, we are working on this part of the CSTC in the near future and conduct thorough testing.

**Closed by fhaag95** 2023-06-21 08:15 UTC
Labels: bug
