### ISSUE TITLE
Lane test feature broken

### ISSUE THREAD

**Issue by LMRupp** [usdAG/cstc#56] opened 2021-10-05 09:25 UTC
The operations test feature seems to be broken:

Steps to reproduce:
1. Paste a request or response into the "Input" field in the upper right corner of the CSTC window
2. Add an operation to the lane, eg. a static string operation

Expected behavior:
The "Output" field in the lower right part of the CSTC window should show the result of the operations applied to the input.

What happens:
The "Output" field remains empty.

When starting burp from the command line, the following error message is shown when the problem occurs:

```
java.lang.NullPointerException: Cannot invoke "burp.gqk.a(burp.guo)" because "this.a" is null
        at burp.gad.a(Unknown Source)
        at burp.gau.c(Unknown Source)
        at burp.cam.h(Unknown Source)
        at burp.bt4.l(Unknown Source)
        at burp.i64.getMessage(Unknown Source)
        at burp.bh5.getMessage(Unknown Source)
        at de.usd.cstchef.view.BurpEditorWrapper.getMessage(BurpEditorWrapper.java:46)
        at de.usd.cstchef.view.RecipePanel$8.run(RecipePanel.java:473)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by fhaag95** [comment] 2023-06-21 08:11
Thanks for reaching out. In the current version we could not reproduce this issue. Maybe it was already fixed by changes made to the CSTC prior. If you still encounter the issue feel free to reopen the Issue.

**Closed by fhaag95** 2023-06-21 08:11 UTC
